region            = "ap-southeast-1"
availability_zone = "ap-southeast-1a"
bucket_prefix     = "pdf-to-brainrot-test"
ami               = "ami-065a492fef70f84b1"
github_repo       = "https://github.com/bookpanda/pdf-2-brainrot"